In [18]:
import pandas as pd

from evaluation_utils import (
    build_eval_artifacts,
    create_test_cases,
    evaluate_ndcg_at_5,
    compare_weight_configs,
)

In [19]:
artifacts = build_eval_artifacts()

print("Eval-artifacts built.")
print(f"N movies in hybrid_features: {len(artifacts['hybrid_features'])}")
print(f"N movies in collaborative-index: {len(artifacts['movie_to_idx'])}")

Eval-artifacts built.
N movies in hybrid_features: 86537
N movies in collaborative-index: 15899

In [20]:
test_cases = create_test_cases(
    ratings=artifacts["ratings"],
    movie_to_idx=artifacts["movie_to_idx"],
    min_positive_movies=5,
    n_users=50,
    seed=42,
)

print(f"Number of test cases: {len(test_cases)}")
test_cases.head()

Number of test cases: 50

   userId  query_movie                                    relevant_movies
0  133147           10                               {296, 380, 292, 300}
1  169691       122916  {115713, 122882, 114180, 85510, 122886, 37386,...
2  148907         1196  {260, 68358, 112556, 68237, 1198, 527, 70286, ...
3   29510         3101         {2752, 1097, 2539, 2028, 1934, 3608, 1721}
4  257427           47  {4105, 4132, 555, 1073, 1089, 6731, 44633, 308...

In [21]:
mean_ndcg_5 = evaluate_ndcg_at_5(
    test_cases=test_cases,
    hybrid_features=artifacts["hybrid_features"],
    tfidf_matrix=artifacts["tfidf_matrix"],
    movie_to_row_idx=artifacts["movie_to_row_idx"],
    item_user_matrix=artifacts["item_user_matrix"],
    movie_to_idx=artifacts["movie_to_idx"],
    idx_to_movie=artifacts["idx_to_movie"],
    knn_model=artifacts["knn_model"],
    collab_weight=0.4,
    content_weight=0.35,
    rating_weight=0.1,
    expert_weight=0.1,
    new_expert_weight=0.05,
    popularity_weight=0.1,
    progress_every=5,
)

mean_ndcg_5

Finished with 5/50 test cases.
Finished with 10/50 test cases.
Finished with 15/50 test cases.
Finished with 20/50 test cases.
Finished with 25/50 test cases.
Finished with 30/50 test cases.
Finished with 35/50 test cases.
Finished with 40/50 test cases.
Finished with 45/50 test cases.
Finished with 50/50 test cases.

0.20811722780713718

In [22]:
configs = [
    {
        "name": "baseline_current",
        "collab_weight": 0.3,
        "content_weight": 0.45,
        "rating_weight": 0.1,
        "expert_weight": 0.1,
        "new_expert_weight": 0.05,
        "progress_every": 5,
    },
    {
        "name": "more_collab",
        "collab_weight": 0.4,
        "content_weight": 0.35,
        "rating_weight": 0.1,
        "expert_weight": 0.1,
        "new_expert_weight": 0.05,
        "progress_every": 5,
    },
    {
        "name": "balanced",
        "collab_weight": 0.35,
        "content_weight": 0.35,
        "rating_weight": 0.1,
        "expert_weight": 0.15,
        "new_expert_weight": 0.05,
        "progress_every": 5,
    },
]

results_df = compare_weight_configs(configs, test_cases, artifacts)
results_df

Running config: baseline_current
Finished with 5/50 test cases.
Finished with 10/50 test cases.
Finished with 15/50 test cases.
Finished with 20/50 test cases.
Finished with 25/50 test cases.
Finished with 30/50 test cases.
Finished with 35/50 test cases.
Finished with 40/50 test cases.
Finished with 45/50 test cases.
Finished with 50/50 test cases.
Running config: more_collab
Finished with 5/50 test cases.
Finished with 10/50 test cases.
Finished with 15/50 test cases.
Finished with 20/50 test cases.
Finished with 25/50 test cases.
Finished with 30/50 test cases.
Finished with 35/50 test cases.
Finished with 40/50 test cases.
Finished with 45/50 test cases.
Finished with 50/50 test cases.
Running config: balanced
Finished with 5/50 test cases.
Finished with 10/50 test cases.
Finished with 15/50 test cases.
Finished with 20/50 test cases.
Finished with 25/50 test cases.
Finished with 30/50 test cases.
Finished with 35/50 test cases.
Finished with 40/50 test cases.
Finished with 45/50 test cases.
Finished with 50/50 test cases.

,name,collab_weight,content_weight,rating_weight,expert_weight,new_expert_weight,progress_every,popularity_weight,ndcg_at_5
0,more_collab,0.40,0.35,0.1,0.10,0.05,5,0.0,0.342104
1,balanced,0.35,0.35,0.1,0.15,0.05,5,0.0,0.307028
2,baseline_current,0.30,0.45,0.1,0.10,0.05,5,0.0,0.208117

In [23]:
configs = [
    {
        "name": "new_baseline (more_collab)",
        "collab_weight": 0.4,
        "content_weight": 0.35,
        "rating_weight": 0.1,
        "expert_weight": 0.1,
        "new_expert_weight": 0.05,
        "progress_every": 5,
    },
    {
        "name": "even_more_collab",
        "collab_weight": 0.5,
        "content_weight": 0.25,
        "rating_weight": 0.1,
        "expert_weight": 0.1,
        "new_expert_weight": 0.05,
        "progress_every": 5,
    },
    {
        "name": "more_expert",
        "collab_weight": 0.30,
        "content_weight": 0.30,
        "rating_weight": 0.1,
        "expert_weight": 0.2,
        "new_expert_weight": 0.1,
        "progress_every": 5,
    },
]

results_df = compare_weight_configs(configs, test_cases, artifacts)
results_df

Running config: new_baseline (more_collab)
Finished with 5/50 test cases.
Finished with 10/50 test cases.
Finished with 15/50 test cases.
Finished with 20/50 test cases.
Finished with 25/50 test cases.
Finished with 30/50 test cases.
Finished with 35/50 test cases.
Finished with 40/50 test cases.
Finished with 45/50 test cases.
Finished with 50/50 test cases.
Running config: even_more_collab
Finished with 5/50 test cases.
Finished with 10/50 test cases.
Finished with 15/50 test cases.
Finished with 20/50 test cases.
Finished with 25/50 test cases.
Finished with 30/50 test cases.
Finished with 35/50 test cases.
Finished with 40/50 test cases.
Finished with 45/50 test cases.
Finished with 50/50 test cases.
Running config: more_expert
Finished with 5/50 test cases.
Finished with 10/50 test cases.
Finished with 15/50 test cases.
Finished with 20/50 test cases.
Finished with 25/50 test cases.
Finished with 30/50 test cases.
Finished with 35/50 test cases.
Finished with 40/50 test cases.
Finished with 45/50 test cases.
Finished with 50/50 test cases.

,name,collab_weight,content_weight,rating_weight,expert_weight,new_expert_weight,progress_every,popularity_weight,ndcg_at_5
0,even_more_collab,0.5,0.25,0.1,0.1,0.05,5,0.0,0.343583
1,new_baseline (more_collab),0.4,0.35,0.1,0.1,0.05,5,0.0,0.342104
2,more_expert,0.3,0.30,0.1,0.2,0.10,5,0.0,0.326313

In [24]:
configs = [
    {
        "name": "new_baseline (more_collab)",
        "collab_weight": 0.4,
        "content_weight": 0.35,
        "rating_weight": 0.1,
        "expert_weight": 0.1,
        "new_expert_weight": 0.05,
        "progress_every": 5,
    },
    {
        "name": "more_content",
        "collab_weight": 0.25,
        "content_weight": 0.5,
        "rating_weight": 0.1,
        "expert_weight": 0.1,
        "new_expert_weight": 0.05,
        "progress_every": 5,
    },
    {
        "name": "flat",
        "collab_weight": 0.2,
        "content_weight": 0.2,
        "rating_weight": 0.2,
        "expert_weight": 0.2,
        "new_expert_weight": 0.2,
        "progress_every": 5,
    },
]

results_df = compare_weight_configs(configs, test_cases, artifacts)
results_df

Running config: new_baseline (more_collab)
Finished with 5/50 test cases.
Finished with 10/50 test cases.
Finished with 15/50 test cases.
Finished with 20/50 test cases.
Finished with 25/50 test cases.
Finished with 30/50 test cases.
Finished with 35/50 test cases.
Finished with 40/50 test cases.
Finished with 45/50 test cases.
Finished with 50/50 test cases.
Running config: more_content
Finished with 5/50 test cases.
Finished with 10/50 test cases.
Finished with 15/50 test cases.
Finished with 20/50 test cases.
Finished with 25/50 test cases.
Finished with 30/50 test cases.
Finished with 35/50 test cases.
Finished with 40/50 test cases.
Finished with 45/50 test cases.
Finished with 50/50 test cases.
Running config: flat
Finished with 5/50 test cases.
Finished with 10/50 test cases.
Finished with 15/50 test cases.
Finished with 20/50 test cases.
Finished with 25/50 test cases.
Finished with 30/50 test cases.
Finished with 35/50 test cases.
Finished with 40/50 test cases.
Finished with 45/50 test cases.
Finished with 50/50 test cases.

,name,collab_weight,content_weight,rating_weight,expert_weight,new_expert_weight,progress_every,popularity_weight,ndcg_at_5
0,flat,0.20,0.20,0.2,0.2,0.20,5,0.0,0.354105
1,new_baseline (more_collab),0.40,0.35,0.1,0.1,0.05,5,0.0,0.342104
2,more_content,0.25,0.50,0.1,0.1,0.05,5,0.0,0.176729

In [25]:
configs = [
    {"name" : "simple",
     "collab_weight" : 0.55,
     "content_weight" : 0.45,
     "rating_weight" : 0.0,
     "expert_weight" : 0.0,
     "new_expert_weight" : 0.0,
     "progress_every" : 5,
     }
]

results_df = compare_weight_configs(configs, test_cases, artifacts)
results_df

Running config: simple
Finished with 5/50 test cases.
Finished with 10/50 test cases.
Finished with 15/50 test cases.
Finished with 20/50 test cases.
Finished with 25/50 test cases.
Finished with 30/50 test cases.
Finished with 35/50 test cases.
Finished with 40/50 test cases.
Finished with 45/50 test cases.
Finished with 50/50 test cases.

,name,collab_weight,content_weight,rating_weight,expert_weight,new_expert_weight,progress_every,popularity_weight,ndcg_at_5
0,simple,0.55,0.45,0.0,0.0,0.0,5,0.0,0.330705

In [27]:
configs = [
    {
        "name": "more_collab",
        "collab_weight": 0.4,
        "content_weight": 0.35,
        "rating_weight": 0.1,
        "expert_weight": 0.1,
        "new_expert_weight": 0.05,
        "popularity_weight": 0.0,
        "progress_every": 5,
    },
    {
        "name": "with_popularity_group",
        "collab_weight": 0.4,
        "content_weight": 0.35,
        "rating_weight": 0.1,
        "expert_weight": 0.1,
        "new_expert_weight": 0.05,
        "popularity_weight": 0.05,
        "progress_every": 5,
    },
    {
        "name": "with_more_popularity_group",
        "collab_weight": 0.4,
        "content_weight": 0.35,
        "rating_weight": 0.1,
        "expert_weight": 0.1,
        "new_expert_weight": 0.05,
        "popularity_weight": 0.1,
        "progress_every": 5,
    },
]

results_df = compare_weight_configs(configs, test_cases, artifacts)
results_df

Running config: more_collab
Finished with 5/50 test cases.
Finished with 10/50 test cases.
Finished with 15/50 test cases.
Finished with 20/50 test cases.
Finished with 25/50 test cases.
Finished with 30/50 test cases.
Finished with 35/50 test cases.
Finished with 40/50 test cases.
Finished with 45/50 test cases.
Finished with 50/50 test cases.
Running config: with_popularity_group
Finished with 5/50 test cases.
Finished with 10/50 test cases.
Finished with 15/50 test cases.
Finished with 20/50 test cases.
Finished with 25/50 test cases.
Finished with 30/50 test cases.
Finished with 35/50 test cases.
Finished with 40/50 test cases.
Finished with 45/50 test cases.
Finished with 50/50 test cases.
Running config: with_more_popularity_group
Finished with 5/50 test cases.
Finished with 10/50 test cases.
Finished with 15/50 test cases.
Finished with 20/50 test cases.
Finished with 25/50 test cases.
Finished with 30/50 test cases.
Finished with 35/50 test cases.
Finished with 40/50 test cases.
Finished with 45/50 test cases.
Finished with 50/50 test cases.

,name,collab_weight,content_weight,rating_weight,expert_weight,new_expert_weight,popularity_weight,progress_every,ndcg_at_5
0,with_more_popularity_group,0.4,0.35,0.1,0.1,0.05,0.10,5,0.359211
1,with_popularity_group,0.4,0.35,0.1,0.1,0.05,0.05,5,0.351162
2,more_collab,0.4,0.35,0.1,0.1,0.05,0.00,5,0.342104

I also tested popularity_group as an additional signal in the evaluation. In the current comparison, both popularity-based variants performed better than the plain more_collab baseline, and the best result was obtained with popularity_weight = 0.10. This popularity-aware configuration was therefore selected as the final model.